name: Longa Whisper OpenAI
dataset:
  train_manifest: ???
  val_manifest: ???
  test_manifest: ???
  eval_set: val
  load_path: null
  load_from_hub: false
  repo_id: null
model:
  pretrained_model: Sunbird/asr-whisper-large-v3-salt
  language: swahili
training_args:
  output_dir: ???
  per_device_train_batch_size: 16
  gradient_accumulation_steps: 1
  learning_rate: 1.0e-05
  warmup_steps: 500
  max_steps: 500000
  gradient_checkpointing: true
  fp16: true
  eval_strategy: steps
  per_device_eval_batch_size: 8
  predict_with_generate: true
  generation_max_length: 225
  save_steps: 1000
  eval_steps: 1000
  logging_steps: 25
  report_to: tensorboard
  load_best_model_at_end: true
  metric_for_best_model: wer
  greater_is_better: false
  push_to_hub: false
  hub_model_id: null
